feat(panel): add '--calcite-panel-content-space' style
Esri/calcite-design-system pull request #10117
Opened 2024-08-20 17:51 UTC by driskull

**Related Issue:** #

## Summary

- add '--calcite-panel-content-space' style.
- add screenshot test

2024-08-20 19:00 UTC, alisonailea requested changes
This token name is not consistent with what is in Figma. I'd like to get @SkyeSeitz and @ashetland's guidance. I think (for now) we should prefer the E2E test for variables over chromatic theming but if you do want to add chromatic tests please use https://github.com/Esri/calcite-design-system/wiki/component-tokens for reference. ~~Also, if you have time could you add the other panel tokens while you're here?~~

~~--calcite-panel-background-color~~
~~--calcite-panel-footer-space~~
~~--calcite-panel-text-color~~

2024-08-20 19:03 UTC, jcfranco commented
> Also, if you have time could you add the other panel tokens while you're here?
> 
> --calcite-panel-background-color
> --calcite-panel-footer-space
> --calcite-panel-text-color

@alisonailea To keep the PR focused and avoid scope creep, let's handle these changes separately.

2024-08-20 20:49 UTC, driskull commented
> This token name is not consistent with what is in Figma. 

How is it not consistent? `calcite-dialog-content-space` was just added and this is nearly identical. Can you elaborate here @alisonailea?

> I think (for now) we should prefer the E2E test for variables over chromatic theming

The e2e test only checks that the property is being applied. It doesn't actually verify things are looking as they are supposed to. Especially when panel is used inside dialog and other components.

2024-08-20 20:50 UTC, driskull commented on packages/calcite-components/src/components/panel/panel.stories.ts
> +export const contentSpace = (): string =>
Why would we avoid testing that this is working visually?

2024-08-21 17:09 UTC, alisonailea commented
It looks like Aaron and Skye updated the Figma UI Kit to align Figma with the `-content-space` variable after I talked to them yesterday, so that's no longer an issue. But when adding tokens it's important to always double check the Figma UI Kit file and talk with design if there are inconsistencies with code.

All we actually care about in the case of variables is that the expected property changes when the variable does, so E2E tests work pretty well. Doing a visual check as well is nice but the exact visual layout could change and the variable would still be valid. Additionally, there are concerns over adding additional Chromatic tests right now which is why we are moving all chromatic tests to a single storybook file `custom-theme`. I just merged the PR so it should be available to use now. Follow the `Card.ts` file for a good example.

2024-08-21 18:03 UTC, driskull commented on packages/calcite-components/src/components/panel/panel.stories.ts
> +export const contentSpace = (): string =>
I'd like to hold off on moving this to a combined story theme for now if possible. There are other theme stories in here as well.

2024-08-21 21:19 UTC, alisonailea approved these changes
🎉

2024-08-21 22:18 UTC, merged