ci(changelog): add deprecation commits to changelog automation
Esri/calcite-design-system pull request #10346
Opened 2024-09-19 00:39 UTC by DitwanP

**Related Issue:** #9975 

## Summary
Adds custom type list to lerna and release-please config files, and add a deprecation type to the list. This should allow for tracking deprecations in the change-logs

2024-09-23 18:28 UTC, DitwanP commented on lerna.json
> +      { "type": "deprecation", "section": "Deprecations" },
Yeah I think thats a bit cleaner for the titles. 👍

2024-09-23 18:31 UTC, jcfranco requested changes
The issue seems primarily focused on documentation, so introducing a brand-new type for deprecations could be confusing (e.g., we sometimes deprecate purely with doc, and other times with a feature or fix). 

The [type object supports specifying a scope](https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.2.0/README.md#type). Could we test if the following would address the request?

```json
 {"type": "docs", "hidden": true},
 {"type": "docs", "scope": "deprecation", "hidden": false},
```

2024-09-23 18:43 UTC, jcfranco commented
Didn't realize I left out my suggestion 😅 (updated now), but let's proceed w/ @benelan's.

2024-09-23 20:17 UTC, DitwanP commented
@jcfranco, @benelan 
> Yeah I like this idea, more specifically can you test if this works:
{ "type": "docs", "scope": "deprecation", "section": "Deprecations" },

So I want to make sure I understand what this suggestion and Franco's are asking for. Would this be a replacement for the deprecation type, so we would instead use the "docs" type with a scope of deprecation?

If so, it should be noted that it the change-log would only pickup deprecation commits with a format like this "**docs(deprecation)**: This is a deprecation...." and would show up under the deprecations section like this:
![image](https://github.com/user-attachments/assets/1fa14014-d68b-4d6c-a41e-ce2b84a17ac6)

Note that the scope would then always be "deprecation" instead of showing more specific scopes like the other change-log types (feat, fix). 
![image](https://github.com/user-attachments/assets/3f8fb474-72e5-4196-98b8-705b7772235c)

2024-09-23 23:50 UTC, jcfranco commented
Solid point. We would definitely lose some flexibility with the `docs(deprecation)` approach. 

@DitwanP @benelan WDYT about tweaking the original solution to be more explicit, like `deprecation-doc` or similar, to indicate it's doc-only?

2024-09-24 22:44 UTC, jcfranco commented
> Do you mean have one type that's for deprecate and another for deprecate-doc?

I was suggesting the latter.

> I thought that in those feat/fix cases is where the deprecate would come into play so that on the changelog there's an explicit section to list what was deprecated, but maybe that's not the case?

We can only use one type per commit, so I don't think we can easily split up deprecation code changes from a `feat`/`fix`. 
For example, how would we use `deprecate` with [this `feat` PR](https://github.com/Esri/calcite-design-system/pull/10202/files)? Maybe I'm missing something? 🤔

2024-09-24 23:01 UTC, DitwanP commented
> For example, how would we use deprecate with [this feat PR](https://github.com/Esri/calcite-design-system/pull/10202/files)? Maybe I'm missing something? 🤔

So I thought something like that would now be "deprecate: remove widthScale...." or deprecate(widthScale, heightScale): something something..."

2024-09-25 00:36 UTC, jcfranco commented
That would work if the change is purely to deprecate a component member, but we often handle deprecations within a `fix` or `feat`. In the example above, the changelog would no longer display a `feat` entry.

2024-09-25 16:49 UTC, DitwanP commented
> That would work if the change is purely to deprecate a component member, but we often handle deprecations within a `fix` or `feat`. In the example above, the changelog would no longer display a `feat` entry.

@jcfranco 

🤔 I get that we currently sometimes handle deprecations like that but I guess I'm confused because I thought we would now just do the deprecation separate from the feature or a fix PRs. 

What do you have in mind for how having `deprecate-docs` would change things? Would it be used for the purely deprecation PRs and we would still sometimes bundle deprecations with feat/fix? Because in those cases we would just end up with the changelog listing deprecations under feat/fix sections instead of deprecations.

2024-09-25 18:06 UTC, jcfranco commented
> I thought we would now just do the deprecation separate from the feature or a fix PRs.

We can, but this adds, IMO, unnecessary overhead. In the example above, we need to add code to handle both the new prop and the deprecated one in the same PR. Not sure how we could separate those cleanly. Also, it'd be odd to not add a deprecation note when the new props are added.

2024-09-25 22:31 UTC, DitwanP commented
@benelan the conversation between Franco and I continued on teams and we wanted your input on the pending solution. We currently are planning to use `deprecate-docs` in the manner described in this pending wiki update:
![image](https://github.com/user-attachments/assets/d7a05752-737e-46eb-9917-f1569a8a35fc)

Do you have any objections to the empty commit option or perhaps a suggestion for another route we could take.

2024-09-26 17:31 UTC, benelan commented
Yeah that works for me. We can add multiple changelog entries from a single PR in release-please:
https://github.com/googleapis/release-please#what-if-my-pr-contains-multiple-fixes-or-features

So we could create the PR title as the type doc/fix/feat, but include a `deprecate` tag as well.

2024-09-26 20:02 UTC, DitwanP commented
@jcfranco I've made the changes based on Ben's suggestions.

Also updated the wording on the pending wiki update to reflect the proposed process,  LMK what you think: 

> When a pull request is strictly intended to deprecate an existing feature or component, use the `deprecate` commit type. This type is reserved for noting changes under the "Deprecations" section of the changelog.

> If deprecations are part of a broader change, such as introducing a new `feature` or making a `fix`, a `deprecate` entry can be added to the body of the PR following the format described in the [release-please documentation]([googleapis/release-please#what-if-my-pr-contains-multiple-fixes-or-features](https://github.com/googleapis/release-please#what-if-my-pr-contains-multiple-fixes-or-features)).

2024-09-26 20:32 UTC, jcfranco commented
That looks great! Thanks to both of youse!

The only note I have is to consider adding some example snippets to the wiki update.

2024-09-26 20:33 UTC, jcfranco approved these changes
📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝
📝⛔⛔⛔⛔📝⛔📝📝📝📝📝⛔📝⛔⛔⛔⛔📝📝⛔⛔⛔📝📝⛔⛔📝📝⛔📝📝📝⛔📝⛔⛔⛔⛔📝⛔📝
📝⛔📝📝⛔📝⛔📝📝📝📝📝⛔📝⛔📝📝📝📝⛔📝📝📝📝⛔📝📝⛔📝⛔⛔📝⛔⛔📝⛔📝📝📝📝⛔📝
📝⛔⛔⛔⛔📝⛔📝📝⛔📝📝⛔📝⛔⛔⛔📝📝📝⛔⛔📝📝⛔📝📝⛔📝⛔📝⛔📝⛔📝⛔⛔⛔📝📝⛔📝
📝⛔📝📝⛔📝⛔📝⛔📝⛔📝⛔📝⛔📝📝📝📝📝📝📝⛔📝⛔📝📝⛔📝⛔📝📝📝⛔📝⛔📝📝📝📝📝📝
📝⛔📝📝⛔📝📝⛔📝📝📝⛔📝📝⛔⛔⛔⛔📝⛔⛔⛔📝📝📝⛔⛔📝📝⛔📝📝📝⛔📝⛔⛔⛔⛔📝⛔📝
📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝📝

2024-09-26 21:21 UTC, merged