refactor: simplify reflected attribute accesses
Esri/calcite-design-system pull request #10356
Opened 2024-09-19 17:49 UTC by maxpatiiuk

Minor refactor - some HTML attributes are reflected to properties.
Thus, we can access properties instead of calling getAttribute/hasAttribute.
Properties are also more type-safe (where as getAttribute string parameter does not have type-checking)

2024-09-19 17:52 UTC, maxpatiiuk commented on packages/calcite-components/src/components/dialog/dialog.tsx
> -  private setContainerEl = (el: HTMLDivElement): void => {
Never read, thus removed

2024-09-19 17:52 UTC, maxpatiiuk commented on packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx
> +  private startInput: HTMLCalciteInputTextElement;
This was causing a type error in Lumina - the ref is assigned to calcite-input-text, but the type here was calcite-input.

2024-09-19 17:52 UTC, maxpatiiuk commented on packages/calcite-components/src/components/input-number/input-number.tsx
> +        enterKeyHint={this.el.enterKeyHint}
`enterkeyhint` attribute reflects to `enterKeyHint` propertie.
Verified in Chrome, Firefox and Safari.

Same for others

2024-09-19 17:52 UTC, maxpatiiuk commented on packages/calcite-components/src/components/input/input.tsx
> +    const autofocus = this.el.autofocus ? true : null;
(optional) This would be even shorter, but less readable:

```suggestion
    const autofocus = this.el.autofocus || null;
```

2024-09-19 18:16 UTC, maxpatiiuk commented on packages/calcite-components/src/components/input-number/input-number.tsx
> +        enterKeyHint={this.el.enterKeyHint}
EDIT: that is true for `<input>` elements.
it is not true for custom elements.
reverting this change

2024-09-19 18:20 UTC, maxpatiiuk commented on packages/calcite-components/src/components/tooltip/tooltip.tsx
> -  hasLoaded = false;
never read

2024-09-19 18:20 UTC, maxpatiiuk commented on packages/calcite-components/src/components/menu/menu.tsx
> -    return this.el.getAttribute("role") || "menubar";
equivalent

2024-09-23 17:03 UTC, jcfranco commented
I think [Firefox ESR](https://whattrainisitnow.com/calendar/) prevents us from using ARIA-related properties (e.g., `ariaExpanded` was [added in FF 119](https://caniuse.com/?search=ariaexpanded)). 

@dasa does this seem accurate to you?

Sidebar: noticed `value-list` (deprecated) currently [uses `ariaLabel`](https://github.com/Esri/calcite-design-system/blame/dev/packages/calcite-components/src/components/value-list/value-list.tsx#L489).

2024-09-23 17:20 UTC, dasa commented
We're planning to only support ESR 128 in our next release: https://whattrainisitnow.com/release/?version=esr

2024-09-23 17:41 UTC, jcfranco requested changes
Thanks for the PR, @maxpatiiuk! 

Along the same lines of https://github.com/Esri/calcite-design-system/pull/10352, since some additional refactors were made to files unrelated to simplifying reflected attribute accesses, can you either:

1. separate non-Host-related refactors to a separate PR? 
2. update the PR title to convey all PR changes?

Thanks!

2024-09-24 19:13 UTC, maxpatiiuk commented
> I think [Firefox ESR](https://whattrainisitnow.com/calendar/) prevents us from using ARIA-related properties (e.g., ariaExpanded was [added in FF 119](https://caniuse.com/?search=ariaexpanded)).

> We're planning to only support ESR 128 in our next release: https://whattrainisitnow.com/release/?version=esr

@jcfranco so if the next release of JS API will drop Firefox 115 ESR support, is Calcite going to do the same for Calcite 3.0 release?
If so, are we ok to use aria properties in this PR or should I revert the change?

2024-09-24 19:22 UTC, maxpatiiuk commented on packages/calcite-components/src/components/functional/Heading.tsx
> -    <HeadingTag class={props.class} key={props.key} level={props.level}>
`level` prop doesn't seem to exist in the DOM?
was it used for styling or testing? if not, we should remove it

---

original discussion in https://github.com/Esri/calcite-design-system/pull/10352#discussion_r1767097375

2024-09-24 22:48 UTC, jcfranco commented
> If so, are we ok to use aria properties in this PR or should I revert the change?

Sorry for not clarifying earlier. We should be good to use ARIA properties if we install this after our September release (scheduled for this upcoming Monday).

2024-09-24 22:50 UTC, jcfranco approved these changes
Awesome stuff, @maxpatiiuk! Thanks! 🚀

2024-09-24 23:16 UTC, merged