feat: add default focus color
Esri/calcite-design-system pull request #10512
Opened 2024-10-09 17:13 UTC by alisonailea

**Related Issue:** #7180 

## Summary

This adds `calcite-color-focus` to replace the deprecated `calcite-ui-focus-color`

2024-10-09 17:18 UTC, geospatialem reviewed
@alisonailea Awesome! 💨 Can you also add in the more related #10510 to the issue context?

2024-10-18 21:07 UTC, jcfranco requested changes
Do we need to generate separate `semantic` output for the default focus color to be added? This change is breaking as it removes exports from the `global` files (causing [this build failure](https://github.com/Esri/calcite-design-system/actions/runs/11336635809/job/31526876046?pr=10512#step:5:608)).

2024-10-18 21:07 UTC, jcfranco commented on packages/calcite-design-tokens/src/$config.ts
> +          export: ["./global.js", "./semantic.js", , "./breakpoints.js"],
Should've caught this sooner, but there's an extra `,` here.

2024-10-18 21:09 UTC, jcfranco commented on packages/calcite-design-tokens/support/tests/__snapshots__/index.spec.ts.snap
> -export const calciteColorBackgroundNone = "rgba(255, 255, 255, 0)";
Also, can you update the snapshot to cover semantic tokens? These are no longer present.

2024-10-29 23:24 UTC, jcfranco approved these changes
👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾
👾🪙👾👾👾🪙👾👾🪙🪙👾👾🪙🪙🪙👾👾🪙🪙🪙👾🪙🪙🪙🪙👾🪙👾
👾🪙🪙👾👾🪙👾🪙👾👾🪙👾👾🪙👾👾🪙👾👾👾👾🪙👾👾👾👾🪙👾
👾🪙👾🪙👾🪙👾🪙👾👾🪙👾👾🪙👾👾🪙👾👾👾👾🪙🪙🪙👾👾🪙👾
👾🪙👾👾🪙🪙👾🪙👾👾🪙👾👾🪙👾👾🪙👾👾👾👾🪙👾👾👾👾👾👾
👾🪙👾👾👾🪙👾👾🪙🪙👾👾🪙🪙🪙👾👾🪙🪙🪙👾🪙🪙🪙🪙👾🪙👾
👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾👾

2024-10-30 18:07 UTC, merged