feat(menu-item): add component tokens
Esri/calcite-design-system pull request #10654
Opened 2024-10-30 21:32 UTC by anveshmekala

**Related Issue:** #7180 

## Summary

2025-01-02 20:42 UTC, alisonailea requested changes

2025-01-02 20:42 UTC, alisonailea commented on packages/calcite-components/src/components/menu-item/menu-item.scss
> +    background-color: var(--calcite-menu-background-color-press, var(--calcite-color-foreground-3));
and here. Remove the state from all tokens on :host

2025-01-02 20:42 UTC, alisonailea commented on packages/calcite-components/src/components/menu/menu.scss
> +  background-color: var(--calcite-menu-background-color, var(--calcite-color-transparent));
I don't think this token is necessary here. The background color is covered by the menu item

2025-01-02 22:27 UTC, anveshmekala commented on packages/calcite-components/src/components/menu-item/menu-item.scss
> +    background-color: var(--calcite-menu-background-color-hover, var(--calcite-color-foreground-2));
Good catch, i had state tokens earlier assuming `menu-item` & `action` can have two different background colors.

2025-01-03 18:38 UTC, anveshmekala commented on packages/calcite-components/src/components/menu-item/menu-item.scss
> +    border-block-end-color: var(--calcite-menu-item-accent-color-hover, var(--calcite-color-border-2));
Q: Do we need to add a  borderBlockEndColor when hovered ? Currently, navigation components do not add any border when hovered. 

@SkyeSeitz , @macandcheese

2025-01-03 19:05 UTC, macandcheese commented on packages/calcite-components/src/components/menu-item/menu-item.scss
> +    border-block-end-color: var(--calcite-menu-item-accent-color-hover, var(--calcite-color-border-2));
I think that makes sense, I think `calcite-menu-item:hover { --calcite-menu-item-accent-color: red }` could be a way to set that if desired for some reason, though correct the pattern doesn't currently have that, so we don't need a standalone state token.

2025-01-04 00:06 UTC, alisonailea approved these changes

2025-01-08 05:15 UTC, merged