feat(accordion-item): custom header and content spacing tokens
Esri/calcite-design-system pull request #10721
Opened 2024-11-13 01:57 UTC by alisonailea

**Related Issue:** #4012 

## Summary

### New Token

--calcite-accordion-item-header-content-space: Specifies the component's `heading` padding.

2024-11-13 16:37 UTC, ashetland commented
Does this address the padding around the content slot or only add a token to the header?

2024-11-13 22:22 UTC, ashetland approved these changes
Visual changes lookin' good!

2024-11-14 00:49 UTC, macandcheese commented
Do we need this header space token to be public? I'd expect only the main content area to have its padding adjusted in this manner. I think we could solve just by adjusting the existing implementation to not use the public property on the header.

2024-11-14 01:14 UTC, alisonailea commented
>Do we need this header space token to be public? I'd expect only the main content area to have its padding adjusted in this manner. I think we could solve just by adjusting the existing implementation to not use the public property on the header.

@macandcheese see Paul's comment here - https://github.com/Esri/calcite-design-system/issues/4012#issuecomment-1367487005

2024-11-14 01:23 UTC, macandcheese commented
> > Do we need this header space token to be public? I'd expect only the main content area to have its padding adjusted in this manner. I think we could solve just by adjusting the existing implementation to not use the public property on the header.
> 
> @macandcheese see Paul's comment here - [#4012 (comment)](https://github.com/Esri/calcite-design-system/issues/4012#issuecomment-1367487005)

Maybe we could confirm? I’m just interpreting that as needing to configure the content area padding without that also affecting the header?

2024-11-14 16:15 UTC, ashetland commented
> > > Do we need this header space token to be public? I'd expect only the main content area to have its padding adjusted in this manner. I think we could solve just by adjusting the existing implementation to not use the public property on the header.
> > 
> > 
> > @macandcheese see Paul's comment here - [#4012 (comment)](https://github.com/Esri/calcite-design-system/issues/4012#issuecomment-1367487005)
> 
> Maybe we could confirm? I’m just interpreting that as needing to configure the content area padding without that also affecting the header?

Agree that we should confirm the need for the header space token. I think I read Paul's comment as asking for separate control, but reading it again, it does seem like the ask is only to control the content padding. This would generally match what we're doing elsewhere, right?

2024-11-14 21:19 UTC, alisonailea commented
@macandcheese and @ashetland I've updated the PR and removed the header token. I agree this makes more sense

2024-11-14 21:46 UTC, macandcheese commented on packages/calcite-components/src/components/accordion-item/accordion-item.scss
This is still applying to the `.header-content` div, at line 78:

```
.header-content,
.content {
  padding: var(
    --calcite-accordion-item-content-space,
    var(
      --calcite-internal-accordion-item-padding,
      var(--calcite-internal-accordion-item-spacing-unit, theme("spacing.2") 0.75rem)
    )
  );
}
```

That div should just use the `--calcite-internal-accordion-item-padding` and not the public one.

2024-11-14 21:52 UTC, macandcheese requested changes
I believe the `.header-content` needs to be separated from `content` to ensure the public css property doesn't apply. 

I think we should also mark this as a breaking change (or at least visual change). Users can of course retain the previous design by using the public css property and it's minor but just for logging purposes.

2024-11-16 03:29 UTC, alisonailea commented on packages/calcite-components/src/components/accordion-item/accordion-item.scss
it is currently using the public property on /dev. Are you saying that should not have the same padding as the content?

2024-11-16 04:08 UTC, alisonailea commented
There were some weird merge conflicts with /dev so I cleaned up the PR to only include the removal of the 0px top padding as was requested in the original issue. If we want to separate the header and content padding that should be a separate issue.

2024-11-16 04:43 UTC, macandcheese commented on packages/calcite-components/src/components/accordion-item/accordion-item.scss
Yeah - the issue in the original issue is that changing the content also affects the header. All the other instances where we have a "content-padding" or equivalent property, it just affects the content area. Here I'd expect the heading padding to remain unchanged when a user adjusts the "content-space" property.

2024-11-18 18:27 UTC, macandcheese approved these changes

2024-11-18 18:27 UTC, macandcheese commented
Looks good - maybe just a tracking issue for the content space comment. Thanks!

2024-11-18 18:39 UTC, alisonailea commented
> Looks good - maybe just a tracking issue for the content space comment. Thanks!

#10762

2024-11-18 20:36 UTC, merged