feat: add icon font files
Esri/calcite-design-system pull request #10996
Opened 2024-12-05 17:51 UTC by allieorth

**Related Issue:** #

## Summary
There has been multiple requests for a font using the Calcite UI icons. This is filling that ask. 
There are 3 font files and corresponding json files to organize and standardize their codepoints.
Also contained in this folder is a codepoints.json for use when updating the font (which will happen every 2 months in line with the release schedule) to keep the codepoints increasing numerically and avoid scrambling codepoints when adding new icons. 

Lastly is the svgs — these are included as they differ from the repo’s svgs because we have to remove icons with multiple paths i.e. opacity.

Take a look at what I have here and let me know if there are improvements to be made. (I am unsure if the SVGs should be in the repo or only on our server, as here they are essentially duplicates?)

I am also hoping to get the codepoints converted to Unicode and included in the searchable ref page to make the font characters searchable. I’m working with @macandcheese  on that [[here](https://github.com/ArcGIS/icon-explorer/issues/6)](https://github.com/ArcGIS/icon-explorer/issues/6)

2024-12-05 19:51 UTC, arowles reviewed
Looks good to me! @benelan  and @jcfranco, it will probably be best to get your 2 cents since there is a lot of files

2024-12-07 00:19 UTC, benelan requested changes
Thanks for putting this together! I have some questions before moving forward with the PR:

1. Should any of these files be added to the NPM package?
2. How were the font files created, is there a script somewhere? If so, we should:
   - add the script(s) to `lib/`
   - document the build process and/or add the required commands as an npm script

I'm hesitant to commit the mostly duplicate SVGs to the monorepo. I'm sure there's a way to programmatically exclude icons with multiple paths. If you can provide more information on the font's build process I should be able to assist with scripting a solution.

I also have a couple initial change requests:

1. Can you change `font/` to `fonts/` so it's aligned with `icons/`
2. Can you move the files in `fonts/font files/` to `fonts/` unless there's a good reason for the extra directory

2024-12-09 18:23 UTC, macandcheese commented
From a doc standpoint - I think we should be a bit defensive here, with any public display. To date, from the component side, we’ve taught folks to use icons via the component and built-in properties, etc - so even if this isn’t “advertised” publicly, adding some guardrails would be nice. 

I also think this strategy of three “sizes” of fonts might need a bit of documentation. As a user - I might expect to use a single icon font file that I can use at any font size. While this is at odds with the “three fixed sizes” approach to some degree, it would be nice to outline our expectations with these.

2024-12-13 23:17 UTC, benelan approved these changes
This LGTM after I automated the build process and reduced the files being committed to the repo.

When building or starting the dev server, the `bin/build-fonts.sh` script will execute, which:

- moves the svg icons into intermediary directories by size, filtering out icons with opacity
- builds the ttf font files
- updates the `fantasticonrc.json` file with the codepoints for any new icons that are added.

The fonts will be bundled into the npm package, which means users will be able to access them from npm or from the `esri-calcite-ui-icons-<VERSION>.tgz` asset attached to the [UI Icon's GitHub Releases](https://github.com/Esri/calcite-design-system/releases/tag/%40esri%2Fcalcite-ui-icons%403.32.0).

@arowles - moving forward, make sure the `fantasticonrc.json` file is updated whenever new icons are added.

@allieorth - please do one more round of testing on your end, and if everything looks good feel free to merge. You won't need to do anything on your end before releases, it's all been automated! If you have questions or concerns, feel free to reach  out here or on Teams. Thanks!

2024-12-13 23:29 UTC, jcfranco approved these changes
🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠
🔠⚛️🔠🔠🔠⚛️🔠🔠⚛️⚛️🔠🔠⚛️⚛️⚛️🔠🔠⚛️⚛️⚛️🔠⚛️⚛️⚛️⚛️🔠⚛️🔠
🔠⚛️⚛️🔠🔠⚛️🔠⚛️🔠🔠⚛️🔠🔠⚛️🔠🔠⚛️🔠🔠🔠🔠⚛️🔠🔠🔠🔠⚛️🔠
🔠⚛️🔠⚛️🔠⚛️🔠⚛️🔠🔠⚛️🔠🔠⚛️🔠🔠⚛️🔠🔠🔠🔠⚛️⚛️⚛️🔠🔠⚛️🔠
🔠⚛️🔠🔠⚛️⚛️🔠⚛️🔠🔠⚛️🔠🔠⚛️🔠🔠⚛️🔠🔠🔠🔠⚛️🔠🔠🔠🔠🔠🔠
🔠⚛️🔠🔠🔠⚛️🔠🔠⚛️⚛️🔠🔠⚛️⚛️⚛️🔠🔠⚛️⚛️⚛️🔠⚛️⚛️⚛️⚛️🔠⚛️🔠
🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠🔠

2025-01-02 17:57 UTC, merged