feat(list-item): deprecate open/close props in favor of expanded/collapsed
Esri/calcite-design-system pull request #11003
Opened 2024-12-06 20:46 UTC by Elijbet

**Related Issue:** #6473

## Summary
Deprecate `open`/`close` props in favor of `expanded`/`collapsed`.

2024-12-06 20:54 UTC, driskull commented on packages/calcite-components/src/components/list-item/list-item.tsx
>    @property({ reflect: true }) closable = false;
I don't think this should be collapsible. It isn't collapsed, it isn't shown at all.

2024-12-06 20:54 UTC, driskull commented on packages/calcite-components/src/components/list-item/list-item.tsx
>    @property({ reflect: true }) closable = false;
I think closed/closable needs to remain as is.

2024-12-06 20:56 UTC, driskull commented on packages/calcite-components/src/components/list-item/list-item.tsx
> +      this.open = this.expanded;
I don't think this is correct. expanded should set expanded, open should set open.

I think what needs to happen is that open and expanded each need a custom setter to set the other one when one is set.

2025-02-13 19:31 UTC, Elijbet commented on packages/calcite-components/src/components/list-item/list-item.tsx
>    @property({ reflect: true }) closable = false;
You're right, it needs to have both `expanded/collapsed` and `closed/closable`.

2025-02-18 21:13 UTC, Elijbet commented on packages/calcite-components/src/components/list-item/list-item.tsx
> +   * When `true`, the item is open to show child components.
@geospatialem, would it be better to say: `When `true`, expands the component and its contents.`?

2025-02-18 21:53 UTC, driskull reviewed
Code changes look good to me,

I think this PR title should be: feat(list-item): add `expanded` property and deprecate `open` property.

2025-02-18 21:53 UTC, driskull commented on readme.md
Can we undo changes here?

2025-02-18 21:55 UTC, driskull reviewed
Can you make sure all other demos and stories are updated with this change as well? Including the HTML files.

2025-02-28 17:19 UTC, jcfranco requested changes
Looking good, @Elijbet! 😎 One more pass and this should be good to land.

Can you also revert the readme changes? Try `git checkout dev -- ./readme.md` (assumes your cwd is `<path-to-projects>/calcite-design-system/packages/calcite-components`).

2025-02-28 17:19 UTC, jcfranco commented on packages/calcite-components/src/components/list-item/list-item.e2e.ts
> +      {
Nice! Can you also update the `reflects` test?

2025-02-28 17:19 UTC, jcfranco commented on packages/calcite-components/src/components/list-item/list-item.e2e.ts
> +  it("should fire calciteListItemToggle event when expanded and collapsed", async () => {
Can you keep the open/closed tests grouped in a "deprecated" describe block? Bonus points if you can extract the tests to be reused between both.

2025-02-28 17:19 UTC, jcfranco commented on packages/calcite-components/src/components/list-item/list-item.tsx
> +    this.expanded = value;
Side note: I think we can start using getters/setters to warn on deprecated prop usage (using [`logger.deprecated`](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/utils/logger.ts#L64-L72)). Could you create an issue for this?

2025-02-28 17:19 UTC, jcfranco commented on packages/calcite-components/src/components/list-item/list-item.tsx
> +   * @deprecated Use `expanded` prop instead.
Can you update external usage of `open` too? `list` has a [few](https://github.com/Esri/calcite-design-system/blob/904623be3cff426e71d51001a29df188a72ea00b/packages/calcite-components/src/components/list/list.tsx#L884) [usages](https://github.com/Esri/calcite-design-system/blob/904623be3cff426e71d51001a29df188a72ea00b/packages/calcite-components/src/components/list/list.tsx#L631). @driskull Are there any other spots that need updating?

2025-02-28 17:20 UTC, jcfranco commented
@Elijbet Can you also update the PR description to match the title/changes?

2025-02-28 17:21 UTC, jcfranco commented on packages/calcite-components/src/components/list-item/list-item.tsx
> +  @property({ reflect: true }) expanded = false;
Can you move this prop so that all public props are in alphabetical order?

2025-02-28 17:21 UTC, driskull commented on packages/calcite-components/src/components/list-item/list-item.tsx
> +   * @deprecated Use `expanded` prop instead.
They should all just be in that file I would suspect.

2025-02-28 18:53 UTC, Elijbet commented
> git checkout dev -- ./readme.md

I tried to roll back the `readme.md` but it won't let me commit it - says it's an empty commit. One suggestion was to edit the PR on GitHub and paste in the code from the main branch so it doesn't do any formatting locally with eslint. I can do that right before merge.

2025-02-28 22:24 UTC, Elijbet commented on packages/calcite-components/src/components/list-item/list-item.tsx
> +    this.expanded = value;
[Add deprecation warnings for deprecated properties](https://github.com/Esri/calcite-design-system/issues/11653#top) #11653

2025-03-03 20:56 UTC, Elijbet commented on packages/calcite-components/src/components/list-item/list-item.e2e.ts
> +  it("should fire calciteListItemToggle event when expanded and collapsed", async () => {
Updating for record here: As we decided, because this ends up touching on too many tests, we'll instead just add a test to check if setting `open` sets `expanded`.

2025-03-05 17:56 UTC, jcfranco approved these changes
Awesome! 🚀

2025-03-05 17:56 UTC, jcfranco commented on packages/calcite-components/src/components/list-item/list-item.e2e.ts
> +  it("should set expanded when open is set", async () => {
Could you update the test name to clarify that it covers the deprecated prop mapping? Also, can you add comments explaining that this test ensures the deprecated prop is correctly mapped and that broader functionality is covered in the `expanded` tests?

2025-03-05 17:56 UTC, jcfranco commented on packages/calcite-components/src/components/list-item/list-item.e2e.ts
> +  describe("calciteListItemToggle event", () => {
✨🏆✨

2025-03-05 20:24 UTC, merged