feat(slider): Implement vertical orientation
Esri/calcite-design-system pull request #11028
Opened 2024-12-11 18:34 UTC by josercarcamo

**Related Issue:** #5522

## Summary
Implemented the vertical orientation for slider.

2024-12-12 02:06 UTC, benelan commented
What happened to #9953? Closing a PR with a lot of context in favor of a new one makes reviewing more difficult because we don't know what's been addressed and what needs further changes/discussion. 

Can you please try maintain a single branch/PR for an issue's changes instead of doing this `branch-v1`, `branch-v2`, etc. style of iteration? Thanks!

2024-12-12 02:10 UTC, benelan commented
It looks like your `v3` PR (#10652) is still open too, which one should we be reviewing?

2024-12-16 16:57 UTC, josercarcamo commented
@benelan the reason I opened other PRs is because it was very difficult to merge Lumina into the old branches. Please review the PRs for which a review is requested.

2025-01-06 20:23 UTC, jcfranco requested changes
Thanks, @josercarcamo! A few changes are needed before we can merge this.

2025-01-06 20:23 UTC, jcfranco commented on packages/calcite-components/src/components/slider/slider.stories.ts
> +        calcite-slider[layout="vertical"] {
With the new vertical layout, the [default styles on the Storybook preview page](https://github.com/Esri/calcite-design-system/blob/b2c976214774490b5a313e1fafc67415fe212b37/packages/calcite-components/.storybook/preview-head.html#L11-L14) should be updated to reduce or eliminate the need for style overrides in individual vertical stories.

2025-01-06 20:23 UTC, jcfranco commented on packages/calcite-components/src/components/slider/slider.e2e.ts
> +          html: `<calcite-slider snap style="width:${sliderWidthFor1To1PixelValueTrack}" layout=${layout}></calcite-slider>`,
This should be using `height`, right?

2025-01-06 20:23 UTC, jcfranco commented on packages/calcite-components/src/components/slider/slider.e2e.ts
> +          html: `<calcite-slider snap style="width:${sliderWidthFor1To1PixelValueTrack}; margin-top: 100px" layout=${layout}></calcite-slider>`,
`margin-top` shouldn't be necessary here. This seems related to the layout issue mentioned earlier.

2025-01-06 20:23 UTC, jcfranco commented on packages/calcite-components/src/components/slider/slider.e2e.ts
> +        expect(inputEvent).toHaveReceivedEventTimes(layout === "horizontal" ? 5 : 6);
FIXME: Could you look into this? Changing layout shouldn't affect event behavior.

2025-01-06 20:23 UTC, jcfranco commented on packages/calcite-components/src/components/slider/slider.e2e.ts
> +          layout === "horizontal"
Can you DRY this up by storing the test x, y variables based on layout and passing them to `click`? Applies to similar test steps.

2025-01-06 20:23 UTC, jcfranco commented on packages/calcite-components/src/components/slider/slider.e2e.ts
> +        layout={layout}`;
Shouldn't this be `layout=${layout}` to use the `layout` var from the `describe.each` block? This would eliminate the need to use `replace` below and keeps tests consistent.

2025-01-14 01:44 UTC, josercarcamo commented on packages/calcite-components/src/components/slider/slider.scss
> +    transform: rotate(-90deg);
Although the content box has been rotated via the rule:

`:host([layout="vertical"]) {
  transform: rotate(-90deg);
}`

CSS interprets the properties as if the scroll bar had not been rotated, so "width" controls the height and "height" controls the width when vertical. Please advise if you know of a way to change the "orientation" of the properties as well.

2025-01-14 17:17 UTC, josercarcamo commented on packages/calcite-components/src/components/slider/slider.tsx
> +    const labelFontSize =
I'm not sure how that would help as I still have to have a conditional to determine whether to pass the "leftLabel" or "rightLabel" to getFontSizeForElement. Please provide a suggestion.

2025-01-14 23:58 UTC, josercarcamo commented on packages/calcite-components/src/components/slider/slider.tsx
> +  private hyphenateVerticalCollidingRangeHandleLabels(): void {
This problem also has to do with rotating the label but not its bounding box. In other words, the label displays horizontally but the bounding box is vertical, so when the hyphen is added, the height of the bounding box is expanded, resulting in the code indicating that the handles are colliding even when visually they may not be.

2025-01-15 19:06 UTC, josercarcamo commented on packages/calcite-components/src/components/slider/slider.tsx
> +    let verticalLabelStaticOffset = 0;
From my understanding, getHostOffset determines the amount by which a label has surpassed the edges of the track. "verticalLabelOffset" offsets the label from the track itself, not its edges.

2025-01-15 19:22 UTC, josercarcamo commented on packages/calcite-components/src/components/slider/slider.stories.ts
> +const verticalAdjustment = "padding-top: 200px; padding-left: 100px; height: 200px";
Both "padding-top" and "padding-left" are for aesthetic reasons, and they both seem to be necessary. Recall that we're trying to fit two sliders on the same page. Removing these styles results in the following:

![image](https://github.com/user-attachments/assets/efbdf40c-fcca-4001-b0a5-b409300377f9)

2025-01-15 23:01 UTC, ashetland commented on packages/calcite-components/src/components/slider/slider.stories.ts
This is what we ended up doing in the UI Kit. It's definitely awkward because both the Label and the validation message could be massively wider than the slider. 
![CleanShot 2025-01-15 at 15 01 11@2x](https://github.com/user-attachments/assets/a261909c-157c-4f5e-a436-a59f378216bd)

2025-01-15 23:15 UTC, josercarcamo commented on packages/calcite-components/src/components/slider/slider.e2e.ts
> +          html: `<calcite-slider snap style="width:${sliderWidthFor1To1PixelValueTrack}" layout=${layout}></calcite-slider>`,
No. "width = height" in vertical orientation.

2025-01-15 23:27 UTC, josercarcamo commented on packages/calcite-components/src/components/slider/slider.e2e.ts
> +          html: `<calcite-slider snap style="width:${sliderWidthFor1To1PixelValueTrack}; margin-top: 100px" layout=${layout}></calcite-slider>`,
It is for aesthetics.

2025-01-16 00:01 UTC, josercarcamo commented on packages/calcite-components/src/components/slider/slider.e2e.ts
> +        expect(inputEvent).toHaveReceivedEventTimes(layout === "horizontal" ? 5 : 6);
The problem is that the upper-left hand corner given by "getElementXY" for horizontal is at value 0 of the slider, but it is at 100 for vertical. This causes one extra event:

![image](https://github.com/user-attachments/assets/e01ddefc-fef8-4603-993c-5d0e509325d7)

![image](https://github.com/user-attachments/assets/33182928-70d5-45aa-8713-cdc756b81f10)

2025-01-16 19:28 UTC, jcfranco commented on packages/calcite-components/src/components/slider/slider.e2e.ts
> +          html: `<calcite-slider snap style="width:${sliderWidthFor1To1PixelValueTrack}" layout=${layout}></calcite-slider>`,
This is confusing, possibly because the implementation is relying heavily on the transform. From a user-perspective, width and height should not change semantics based on an option.

Let's discuss this further today.

2025-01-16 19:28 UTC, jcfranco commented on packages/calcite-components/src/components/slider/slider.scss
> +    transform: rotate(-90deg);
I'm not sure I follow the proposed approach, but let's discuss this further today.

2025-01-16 19:28 UTC, jcfranco commented on packages/calcite-components/src/components/slider/slider.tsx
> +    let verticalLabelStaticOffset = 0;
Gotcha. Thanks for clarifying.

2025-01-16 22:24 UTC, josercarcamo commented on packages/calcite-components/src/components/slider/slider.e2e.ts
> +          html: `<calcite-slider snap style="width:${sliderWidthFor1To1PixelValueTrack}; margin-top: 100px" layout=${layout}></calcite-slider>`,
I guess I misspoke: a part of the vertical slider could be outside the bounds of the window and not be clickable, so it must be moved downward.

2025-01-17 00:07 UTC, josercarcamo commented
After meeting with @jcfranco, we've decided to seek an alternative implementation and pause this issue at this time.

2025-09-16 20:43 UTC, closed without merging