feat(pagination): add component tokens
Esri/calcite-design-system pull request #11157
Opened 2024-12-28 00:44 UTC by aPreciado88

**Related Issue:** [#7180](https://github.com/Esri/calcite-design-system/issues/7180)

## Summary

Add `pagination` component tokens.

`--calcite-pagination-spacing`: Specifies the amount of left and right margin spacing between each item.
`--calcite-pagination-width`: Specifies the width of each item.
`--calcite-pagination-color`: Specifies the component's item color.
`--calcite-pagination-selected-color-hover`: Specifies the component's item color when hovered or selected.
`--calcite-pagination-hover-bottom-border-color`: Specifies the component's item bottom border color when hovered.
`--calcite-pagination-selected-bottom-border-color`: Specifies the component's item bottom border color when selected.
`--calcite-pagination-active-background-color`: Specifies the component's item background color when active.
`--calcite-pagination-hover-chevron-background-color`: Specifies the component's chevron item background color when hovered.

2024-12-30 18:23 UTC, alisonailea requested changes
Please refer to the token naming documentation for naming component tokens

2024-12-30 18:23 UTC, alisonailea commented on packages/calcite-components/src/components/pagination/pagination.scss
> + * @prop --calcite-pagination-width: Specifies the width of each item.
This should be `pagination-size`

2024-12-30 18:23 UTC, alisonailea commented on packages/calcite-components/src/components/pagination/pagination.scss
> + * @prop --calcite-pagination-hover-bottom-border-color: Specifies the component's item bottom border color when hovered.
This should be `--calcite-pagination-color-border-hover`

2024-12-30 18:23 UTC, alisonailea commented on packages/calcite-components/src/components/pagination/pagination.scss
> + * @prop --calcite-pagination-selected-bottom-border-color: Specifies the component's item bottom border color when selected.
this should be `--calcite-pagination-color-border-active`

2024-12-30 18:23 UTC, alisonailea commented on packages/calcite-components/src/components/pagination/pagination.scss
> + * @prop --calcite-pagination-active-background-color: Specifies the component's item background color when active.
`--calcite-pagination-color-background-color`

2024-12-30 18:23 UTC, alisonailea commented on packages/calcite-components/src/components/pagination/pagination.scss
> + * @prop --calcite-pagination-hover-chevron-background-color: Specifies the component's chevron item background color when hovered.
`--calcite-pagination-chevron-color-background-hover`

2024-12-30 18:23 UTC, alisonailea commented on packages/calcite-components/src/components/pagination/pagination.scss
> + * @prop --calcite-pagination-selected-color-hover: Specifies the component's item color when hovered or selected.
This can be simplified down to `--calcite-pagination-color-hover`

2024-12-30 18:23 UTC, alisonailea commented on packages/calcite-components/src/components/pagination/pagination.scss
> +    --width: theme("width.6");
you should not assign tokens inside components unless they are `-internal`

2024-12-30 18:23 UTC, alisonailea commented on packages/calcite-components/src/components/pagination/pagination.scss
> +    --width: theme("width.8");
you should not assign tokens inside components unless they are `-internal`

2024-12-30 18:23 UTC, alisonailea commented on packages/calcite-components/src/components/pagination/pagination.scss
> +    --width: theme("width.11");
you should not assign tokens inside components unless they are `-internal`

2025-01-04 00:50 UTC, aPreciado88 commented
@alisonailea I'm having issues with some token e2e tests, could you please take a look?

2025-01-10 22:42 UTC, macandcheese commented on packages/calcite-components/src/components/pagination/pagination.scss
> + * @prop --calcite-pagination-spacing: Specifies the amount of left and right margin spacing between each item.
cc @SkyeSeitz / @ashetland - What is the reason for allowing this gap to be customized? Seems like even for "low count" pagination, we'd want to maintain the spacing.

Similar q for "-size" - maybe not needed...

2025-01-10 22:43 UTC, SkyeSeitz commented on packages/calcite-components/src/components/pagination/pagination.scss
> + * @prop --calcite-pagination-spacing: Specifies the amount of left and right margin spacing between each item.
+1

2025-01-13 17:31 UTC, alisonailea approved these changes

2025-01-13 17:43 UTC, macandcheese commented on packages/calcite-components/src/components/pagination/pagination.scss
> + * @prop --calcite-pagination-color-background: Specifies the component's item background color when active.
Should this be "background-color" to match other components?

2025-01-13 20:23 UTC, alisonailea commented on packages/calcite-components/src/components/pagination/pagination.scss
> + * @prop --calcite-pagination-color-background: Specifies the component's item background color when active.
yes I agree. Thanks for the catch Adam

2025-01-13 21:18 UTC, aPreciado88 commented
@ashetland @SkyeSeitz It looks like these are the usual false positive screenshots. Can you please confirm?

2025-01-13 21:26 UTC, ashetland commented
Yep, all false positives.

2025-01-13 21:43 UTC, merged