feat(notice): make component responsive
Esri/calcite-design-system pull request #7736
Opened 2023-09-13 17:22 UTC by jcfranco

**Related Issue:** #6779 

## Summary

Updates notice to be responsive per the design spec.

## Additional changes

* simplified class names (`notice` prefix is no longer necessary)
* `requestedIcon` is now computed at render time to simplify component 
* clean up test story

2023-09-18 22:08 UTC, driskull requested changes

2023-09-18 22:08 UTC, driskull commented on packages/calcite-components/src/components/notice/notice.scss
> +  container: host / inline-size;
I like `responsive-container / inline-size`. I think that would work well for every component.

2023-09-18 22:08 UTC, driskull commented on packages/calcite-components/src/components/notice/resources.ts
>    close: "notice-close",
This class needs to be updated.

2023-09-18 22:08 UTC, driskull commented on packages/calcite-components/src/components/notice/resources.ts
>    icon: "notice-icon",
This class needs to be updated.

2023-09-18 22:30 UTC, driskull approved these changes
Code changes look good!

2023-09-19 20:50 UTC, jcfranco commented
@macandcheese @ashetland @SkyeSeitz Could you review the [visual changes](https://www.chromatic.com/build?appId=6266d45509d7eb004aa254fb&number=2513)? 🙇

2023-09-28 03:37 UTC, jcfranco commented
Closing per https://github.com/Esri/calcite-design-system/issues/6779#issuecomment-1730745134.

2023-09-28 03:37 UTC, closed without merging