feat(popover): add component tokens
Esri/calcite-design-system pull request #8642
Opened 2024-01-25 04:53 UTC by Elijbet

**Related Issue:** #7180

## Summary
Adds the following component tokens:

```
--calcite-popover-background-color
--calcite-popover-border-color
--calcite-popover-border-inline-end-color
--calcite-popover-font-size
--calcite-popover-text-color
--calcite-popover-z-index
```

2024-01-25 14:01 UTC, macandcheese commented on packages/calcite-components/src/components/popover/popover.scss
> +* @prop --calcite-popover-border-inline-end-color: The border color of the component.
I think we can use a single border color and a single corner radius, not split by side.

2024-01-25 14:07 UTC, macandcheese commented on packages/calcite-components/src/components/popover/popover.scss
> +* @prop --calcite-popover-font-size: The font size of `calcite-option`s in the component.
I think this could be set with pre existing global vars, not sure if we need the font size per component. Cc @alisonailea to confirm / disconfirm.

2024-01-25 20:55 UTC, Elijbet commented on packages/calcite-components/src/components/popover/popover.scss
> - */
Changed the base.

2024-01-25 22:46 UTC, alisonailea requested changes

2024-01-25 22:46 UTC, alisonailea commented on packages/calcite-components/src/components/popover/popover.scss
> +  @apply rounded
rounded be replaced with a `border-radius: var(--calcite-corner-radius-round)`

2024-01-25 22:46 UTC, alisonailea commented on packages/calcite-components/src/components/popover/popover.scss
> +  --calcite-popover-background-color: var(--calcite-color-foreground-1);
component tokens should be assigned at `:host`

2024-01-25 22:46 UTC, alisonailea commented on packages/calcite-components/src/components/popover/popover.scss
> +  --calcite-popover-border-color: var(--calcite-color-border-3);
set at `:host`

2024-01-29 17:37 UTC, macandcheese commented on packages/calcite-components/src/components/popover/popover.scss
> +* @prop --calcite-popover-font-size: The font size of the component.
Should this specify `-heading-font-size` ?

2024-02-09 00:44 UTC, alisonailea requested changes

2024-02-09 00:44 UTC, alisonailea commented on packages/calcite-components/src/components/popover/popover.scss
> +* @prop --calcite-popover-border-radius: The start end border radius of the component.
`--calcite-popover-corner-radius`

2024-02-09 00:44 UTC, alisonailea commented on packages/calcite-components/src/components/popover/popover.scss
> +* @prop --calcite-popover-font-size: The font size of the component.
Font-size shouldn't be a component token

2024-02-09 00:44 UTC, alisonailea commented on packages/calcite-components/src/components/popover/popover.scss
> +  --calcite-popover-text-color: var(--calcite-color-text-1);
all component tokens must be set at `:host`

2024-02-09 00:44 UTC, alisonailea commented on packages/calcite-components/src/components/popover/popover.scss
> +  --calcite-popover-border-radius: : theme("borderRadius.DEFAULT");
component tokens should only be set at `:host` and this should be `--calcite-popover-corner-radius: var(--calcite-border-radius-round);`

2024-02-16 00:07 UTC, alisonailea requested changes

2024-02-16 00:23 UTC, alisonailea approved these changes
One small thing for non-breaking changes on the z-index. Looks good 🎉

2024-02-16 00:23 UTC, alisonailea commented on packages/calcite-components/src/components/popover/popover.scss
> +  --calcite-floating-ui-z-index: var(--calcite-z-index-popup);
for non-breaking changes I just realized this should be

```
--calcite-floating-ui-z-index: var(--calcite-popover-z-index, var(--calcite-z-index-popup));
```

2024-02-16 00:25 UTC, macandcheese commented on packages/calcite-components/src/components/popover/popover.scss
> +* @prop --calcite-popover-corner-radius: The start end border radius of the component.
Is this description accurate?

2024-02-16 00:33 UTC, merged

2024-02-16 18:05 UTC, driskull commented
@Elijbet @alisonailea shouldn't these be converted to tokens?

```scss
:host([scale="s"]) {
  .heading {
    @apply text-n1-wrap
    px-3
    py-2;
  }
}

:host([scale="m"]) {
  .heading {
    @apply text-0-wrap
    px-4
    py-3;
  }
}

:host([scale="l"]) {
  .heading {
    @apply text-1-wrap
    px-5
    py-4;
  }
}
```

2024-02-16 18:07 UTC, alisonailea commented
> @Elijbet @alisonailea shouldn't these be converted to tokens?

No. We don't want to expose font size and padding as component tokens in most cases at the moment.

2024-02-16 18:10 UTC, driskull commented
What about border width?

```
 @apply border
    border-solid;
```

2024-02-16 18:59 UTC, driskull commented
Should we add a story for testing this? I notice the popover tail isn't being themed properly.