fix(input-date-picker) updated chevron icons colors to be ui-text-3 w…
Esri/calcite-design-system pull request #9146
Opened 2024-04-17 23:09 UTC by aPreciado88

Fixed for https://github.com/Esri/calcite-design-system/issues/7712

Bug:
Input Date Picker's chevrons are black in all states.

Fix:
Updated chevron colors to be ui-text-3 when idle and ui-text-1 when hovered or pressed.

2024-04-18 00:04 UTC, benelan reviewed
First PR lets go! :tada: 

The PR title is a bit too long and it shouldn't end with any punctuation. Also, we want to keep implementation details out of the PR title. Maybe change it to something like:

> fix(input-date-picker): consistent chevron icon color

The implementation details (like the design tokens used) can go in the PR body. And the tokens should be `--calcite-color-text-N` like you have in the code, rather than the legacy `--calcite-ui-text-N` tokens that are currently in the PR title/body.

Once you are done making changes, add the `pr ready for visual snapshots` label to run Chromatic.

2024-04-18 00:18 UTC, benelan requested changes
I took a closer look at the issue, and it doesn't say anything about the `open` property effecting the chevron color. For example, the current implementation wouldn't work for the Figma design's last example:

![image](https://github.com/Esri/calcite-design-system/assets/10986395/44825e51-e0d2-46ad-aadd-7cc15a2cc3fd)

Can you take another look? The `:focus` and/or `:active` pseudo-classes may do what we want.

2024-04-18 17:20 UTC, aPreciado88 commented on packages/calcite-components/src/components/input-date-picker/input-date-picker.tsx
> +          class={open ? "chevron-icon-up" : "chevron-icon-down"}
I consolidated this css into a single class and added it to [resources.ts](https://github.com/Esri/calcite-design-system/blob/main/packages/calcite-components/src/components/input-date-picker/resources.ts).

2024-04-18 18:34 UTC, benelan approved these changes
Nice changes, code LGTM! cc @ashetland for snapshot review

2024-04-18 19:13 UTC, ashetland commented
> Nice changes, code LGTM! cc @ashetland for snapshot review

I'm going to approve the screenshots as all the changes are expected, but the change to `text.1` is only happening while I hover on the icon. It should change onHover and onFocus of the entire input. See PR #8955.

2024-04-18 21:25 UTC, aPreciado88 commented
@ashetland I updated the component to change the chevron's color when the input is hovered.

2024-04-18 23:04 UTC, benelan requested changes
@ashetland mentioned text-1 should be applied on `:focus` too

2024-04-18 23:13 UTC, aPreciado88 commented
@ashetland I updated the component to apply text-1 on :hover, :active and :focus

2024-04-19 00:55 UTC, benelan approved these changes
LGTM!

2024-04-19 15:33 UTC, ashetland commented
Heyo, I'm still only seeing it on hover.

2024-04-19 16:36 UTC, jcfranco commented
@aPreciado88 Can you update the PR title (specifically, the [description part](https://kapeli.com/cheat_sheets/Conventional_Commits.docset/Contents/Resources/Documents/index#:~:text=Commit%20Message%20Structure)) to use the imperative, present tense per the [conventions](https://github.com/ionic-team/stencil/blob/main/CONTRIBUTING.md?rgh-link-date=2024-04-03T00%3A01%3A43Z#subject) we link to in our contributing doc? You can look at previous [commits on `main`](https://github.com/Esri/calcite-design-system/commits/main) as examples.

2024-04-19 17:17 UTC, aPreciado88 commented
@jcfranco I updated the title! Please let me know if that looks good.

2024-04-19 17:35 UTC, ashetland commented
🤘🚀🚢🎉

2024-04-23 16:58 UTC, merged