test(block, block-section): add component token E2E tests
Esri/calcite-design-system pull request #9685
Opened 2024-06-25 19:25 UTC by jcfranco

**Related Issue:** #7180

## Summary

✨🧪✨

2024-06-26 20:12 UTC, alisonailea requested changes
Can you recheck these tests in debugger mode?

2024-06-26 20:12 UTC, alisonailea commented on packages/calcite-components/src/components/block-section/block-section.e2e.ts
> +        "--calcite-block-section-switch-track-border-color": {
this variable isn't being applied.

2024-06-26 22:10 UTC, jcfranco commented on packages/calcite-components/src/components/block-section/block-section.e2e.ts
> +        "--calcite-block-section-status-icon-color": {
> this is being overwritten by .status-icon.valid

This is not accurate. Internal, fallback, values are assigned when valid/invalid, but `--calcite-block-section-status-icon-color` has higher precedence. 

![Screenshot 2024-06-26 at 3 06 10 PM](https://github.com/Esri/calcite-design-system/assets/197440/678101c3-1964-4d4a-a1bb-42ca2fb46aa0)



LMK if I'm missing something.

2024-06-26 22:10 UTC, jcfranco commented on packages/calcite-components/src/components/block-section/block-section.e2e.ts
> +      themed(html`<calcite-block-section heading="heading" description="description"></calcite-block-section>`, {
Fixed!

2024-06-26 22:10 UTC, jcfranco commented on packages/calcite-components/src/components/block-section/block-section.e2e.ts
> +        "--calcite-block-section-heading-text-color-hover": {
Fixed!

2024-06-26 22:10 UTC, jcfranco commented on packages/calcite-components/src/components/block-section/block-section.e2e.ts
> +        "--calcite-block-section-switch-track-border-color": {
Fixed!

2024-06-28 16:53 UTC, alisonailea commented on packages/calcite-components/src/components/block-section/block-section.scss
>   * @prop --calcite-block-section-switch-handle-border-color: Specifies the border color of the switch handle.
Ah missed that thanks!

2024-06-28 16:59 UTC, alisonailea approved these changes

2024-06-28 18:03 UTC, merged