fix(tile): center align contentTop and contentBottom slots when alignment prop equals "center"
Esri/calcite-design-system pull request #9732
Opened 2024-07-03 18:07 UTC by aPreciado88

**Related Issue:** [#9540](https://github.com/Esri/calcite-design-system/issues/9540)

## Summary
This updates the `tile` component to center align `content-top` and `content-bottom` slots when the `alignment` prop is equal to `"center"`

2024-07-03 18:40 UTC, eriklharper requested changes
Also, could you add centered examples for both the `content-top` and `content-bottom` examples in the demo page?  You should be able to just duplicate the 2 rows for each of those slots and simply add `alignment="center"` to each tile instance in the html and the word "centered" to the heading.  That will be nice to be able to reference later.  We should also add those to the all variants story too, but because of the icon rendering issues, it may not be picked up properly by Chromatic.

2024-07-03 19:56 UTC, SkyeSeitz commented on packages/calcite-components/src/components/tile/tile.scss
> +  slot[name="content-bottom"]::slotted(*) {
Agreed on keeping the rule to avoid any visual breaking change on these deprecated slots. Thanks, Erik!

2024-07-12 16:45 UTC, eriklharper approved these changes
👍 LGTM

2024-07-12 17:18 UTC, merged

2024-07-12 17:19 UTC, jcfranco commented
Should this have another round of screenshots? It looks like stories were updated prior to the `skip visual snapshots` label being applied.